[package]
name = "webcrawler-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
url = "2.2.1"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12.0"
crossbeam-deque = "0.8.0"
crossbeam-utils = "0.8.3"
